// Regenerates lib/abi.js from the compiled contract artifacts.
// Run after `npx hardhat compile` in ../contracts:  npm run generate:abi
import { readFileSync, writeFileSync } from 'node:fs';

const load = (p) => JSON.parse(readFileSync(new URL(`../../contracts/artifacts/contracts/${p}`, import.meta.url))).abi;
const pick = (abi, names) => abi.filter((e) => (e.type === 'function' && names.has(e.name)) || e.type === 'error' || e.type === 'event');

const hunt = pick(load('hunt/RiddlenHunt.sol/RiddlenHunt.json'), new Set([
  'riddleCount', 'getRiddle', 'getToken', 'owed', 'reserved', 'available', 'mintPrice', 'revealDelay',
  'potByDifficulty', 'claimFee', 'attemptStep', 'firstFinderBps', 'finisherWindow', 'rollCount', 'verifyFragment',
  'domainSeparator', 'nft', 'commitments',
  'open', 'mint', 'attempt', 'claim', 'settle', 'collect', 'withdraw',
]));
const huntNft = pick(load('hunt/HuntNFT.sol/HuntNFT.json'), new Set([
  'balanceOf', 'ownerOf', 'tokensOf', 'nextId', 'tokenURI', 'totalSupply', 'transferFrom', 'safeTransferFrom',
])).filter((e) => e.type !== 'event' || e.name === 'Transfer');
const commitments = pick(load('hunt/HuntCommitments.sol/HuntCommitments.json'), new Set([
  'mapRoot', 'prizeCommitment', 'launchAt', 'basePrice', 'halvingPeriod', 'totalRiddles', 'minReleaseSpacing', 'mintPriceAt',
]));

const FAUCET_ABI = [
  { type: 'function', name: 'claim', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'canClaim', stateMutability: 'view', inputs: [{ type: 'address', name: 'who' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'claimAmount', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'FaucetEmpty', inputs: [{ type: 'uint256', name: 'balance' }] },
];
const ERC20_ABI = [
  { type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
  { type: 'error', name: 'InsufficientBalance', inputs: [{ type: 'address', name: 'user' }, { type: 'uint256', name: 'required' }, { type: 'uint256', name: 'available' }] },
  { type: 'error', name: 'DailyBurnLimitExceeded', inputs: [{ type: 'uint256', name: 'requested' }, { type: 'uint256', name: 'dailyLimit' }] },
  { type: 'error', name: 'SingleBurnLimitExceeded', inputs: [{ type: 'uint256', name: 'requested' }, { type: 'uint256', name: 'singleLimit' }] },
  { type: 'error', name: 'EnforcedPause', inputs: [] },
];

const j = (x) => JSON.stringify(x, null, 2);
writeFileSync(new URL('../lib/abi.js', import.meta.url),
  `// Generated by scripts/generate-abi.mjs. Do not edit by hand.\n` +
  `export const HUNT_ABI = ${j(hunt)};\n` +
  `export const HUNT_NFT_ABI = ${j(huntNft)};\n` +
  `export const HUNT_COMMITMENTS_ABI = ${j(commitments)};\n` +
  `export const FAUCET_ABI = ${j(FAUCET_ABI)};\n` +
  `export const ERC20_ABI = ${j(ERC20_ABI)};\n`);
console.log(`lib/abi.js: hunt ${hunt.length}, nft ${huntNft.length}, commitments ${commitments.length}`);
