// Regenerates lib/abi.js from the compiled StumpTheMachine artifact.
// Run after `npx hardhat compile` in ../contracts:  npm run generate:abi
import { readFileSync, writeFileSync } from 'node:fs';

const artifact = JSON.parse(readFileSync(
  new URL('../../contracts/artifacts/contracts/nft/StumpTheMachine.sol/StumpTheMachine.json', import.meta.url),
));
const FUNCTIONS = new Set([
  'challengeCount', 'getChallenge', 'getReveals', 'getEntry', 'owed', 'reserved', 'available',
  'poolByDifficulty', 'entryCostByDifficulty', 'REVEAL_WINDOW', 'MIN_SOLVE_TIME', 'MAX_ANSWERS', 'isAccepted',
  'submit', 'revealAnswer', 'enter', 'sealGuess', 'revealGuess', 'finalize', 'claimRefund', 'withdraw',
]);
const abi = artifact.abi.filter((e) => (e.type === 'function' && FUNCTIONS.has(e.name)) || e.type === 'error');

const FAUCET_ABI = [
  { type: 'function', name: 'claim', stateMutability: 'nonpayable', inputs: [], outputs: [] },
  { type: 'function', name: 'canClaim', stateMutability: 'view', inputs: [{ type: 'address', name: 'who' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'claimAmount', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'FaucetEmpty', inputs: [{ type: 'uint256', name: 'balance' }] },
];
const ERC20_ABI = [
  { type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }] },
];

writeFileSync(new URL('../lib/abi.js', import.meta.url),
  `// Generated by scripts/generate-abi.mjs from StumpTheMachine. Do not edit by hand.\n` +
  `export const STUMP_ABI = ${JSON.stringify(abi, null, 2)};\n` +
  `export const FAUCET_ABI = ${JSON.stringify(FAUCET_ABI, null, 2)};\n` +
  `export const ERC20_ABI = ${JSON.stringify(ERC20_ABI, null, 2)};\n`);
console.log(`lib/abi.js: ${abi.length} game entries`);
